/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backbtn: typeof import('./../../src/components/backbtn/index.vue')['default']
    Ceshi: typeof import('./../../src/components/ceshi.vue')['default']
    DialogBox: typeof import('./../../src/components/dialogBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YjsTable1: typeof import('./../../src/components/yjs/table/1/index.vue')['default']
  }
}
