/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const SetUnitConversion: typeof import('../../src/api/methods.js').SetUnitConversion
  const SetUnitConversion2: typeof import('../../src/api/methods.js').SetUnitConversion2
  const accAdd: typeof import('../../src/api/methods.js').accAdd
  const accMul: typeof import('../../src/api/methods.js').accMul
  const accSub: typeof import('../../src/api/methods.js').accSub
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const accp: typeof import('../../src/api/methods.js').accp
  const axios: typeof import('../../src/api/axios').default
  const closeModel: typeof import('../../src/api/dialog.js').closeModel
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const deepCopy: typeof import('../../src/api/methods.js').deepCopy
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const downloadFile: typeof import('../../src/api/methods.js').downloadFile
  const ecahrts_hh: typeof import('../../src/api/methods.js').ecahrts_hh
  const echarts_tooltip: typeof import('../../src/api/methods.js').echarts_tooltip
  const effectScope: typeof import('vue').effectScope
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getFloat: typeof import('../../src/api/methods.js').getFloat
  const getLocal: typeof import('../../src/api/methods.js').getLocal
  const getMapArea: typeof import('../../src/api/methods.js').getMapArea
  const getRandomNumber: typeof import('../../src/api/methods.js').getRandomNumber
  const getSelectWidth: typeof import('../../src/api/methods.js').getSelectWidth
  const getYearList: typeof import('../../src/api/methods.js').getYearList
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const qfw: typeof import('../../src/api/methods.js').qfw
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const refreshToken: typeof import('../../src/api/methods.js').refreshToken
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setLocal: typeof import('../../src/api/methods.js').setLocal
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showModel: typeof import('../../src/api/dialog.js').showModel
  const storeToRefs: typeof import('pinia').storeToRefs
  const stores: typeof import('../../src/stores/index').default
  const swjgdmls: typeof import('../../src/api/methods.js').swjgdmls
  const toFixedFn: typeof import('../../src/api/methods.js').toFixedFn
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDialog: typeof import('naive-ui').useDialog
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useLoadingBar: typeof import('naive-ui').useLoadingBar
  const useMessage: typeof import('naive-ui').useMessage
  const useModel: typeof import('vue').useModel
  const useNotification: typeof import('naive-ui').useNotification
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}
