/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backbtn: typeof import('./../../src/components/backbtn/index.vue')['default']
    DialogBox: typeof import('./../../src/components/dialogBox.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    PublicTable: typeof import('./../../src/components/publicTable/index.vue')['default']
    PublicTabs: typeof import('./../../src/components/publicTabs/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YjsCard1: typeof import('./../../src/components/yjs/card/1/index.vue')['default']
  }
}
